version: "3.9"

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: